version: '3'

services:
  rails:
    image: joaonasser/chatfy:latest
    env_file: .env
    ports:
      - '80:3000'
    environment:
      - EXECJS_RUNTIME=Disabled
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command:
      [
        'bundle',
        'exec',
        'rails',
        's',
        '-p',
        '3000',
        '-b',
        '0.0.0.0'
      ]
    volumes:
      - /data/storage:/app/storage

  sidekiq:
    image: joaonasser/chatfy:latest
    env_file: .env
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command:
      [
        'bundle',
        'exec',
        'sidekiq',
        '-C',
        'config/sidekiq.yml'
      ]
    volumes:
      - /data/storage:/app/storage
