name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Build and Push Docker Image
        run: |
            docker build -t "${{ secrets.DOCKERHUB_USERNAME }}"/chatfy:latest .
            docker push "${{ secrets.DOCKERHUB_USERNAME }}"/chatfy:latest