name: Push to ecr registry

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin "${{ secrets.ECR_REPOSITORY }}"

      - name: Build Docker Image
        run: |
            docker build -t chatfy .
            docker tag chatfy:latest "${{ secrets.ECR_REPOSITORY }}"/chatfy:latest

      - name: push image
        run: docker push "${{ secrets.ECR_REPOSITORY }}"/chatfy:latest