name: Hourly restarter Job

on:
  schedule:
    - cron: '15 * * * *'  

jobs:
  run-cron-job:
    runs-on: self-hosted

    steps:

      - name: Restart container
        run: |
          cd /home/ec2-user/chatwoot
          docker-compose down && docker-compose build && docker-compose up -d